### ISSUE TITLE
Plot the graph representation

### ISSUE THREAD

**Issue by windrise** [tjiagoM/spatio-temporal-brain#21]
I'm interested in your work and appreciate it. Can you tell me about how to visualize the graph representation like the Fig. 1 (or Fig. 6) in your paper.
I am looking forward to your kind reply.
Thanks in advance.

**Comment by tjiagoM** [comment]
Hello and thanks for the interest in our work!

With regards to the graph visualisation you mention, you can see my attempts at exploring the `graph-tool` package here (with short installation instructions): https://github.com/tjiagoM/spatio-temporal-brain/blob/master/post_analysis/graph-tool.ipynb

You can see I tried other visualisation approaches which were not included in the paper using this package. Unfortunately, I found that it was not easy to get something like these plots in a controlled way, and had to manually remove some arrows from the image in Inkscape, as I was not able to do that programmatically. 

If you are interested in these type of plots, I recommend you search for "connectogram plot", as there are other tools online. I ended up using this one because of the Python support, but I recognise there are more out there which could be more useful for you.
